### ISSUE TITLE
[Ruta - Ignorar el sonido] No permite seguir la historia

### ISSUE THREAD

**Issue by franciscoduro** [LucioRuixo/DVJ3-VisualNovel#1]
Cuando elegimos en la ruta de la historia: Ignorar el ruido, sean cuales sean las opciones que elijamos luego nos lleva a una escena final en la que nos encontramos con un nuevo personaje, luego de esa escena la historia no continúa.

Pasos para reproducir: 
1 Seguir la ruta de la historia desde --> **Ignorar el sonido** 
2 Continuar la historia hasta decidir entre las opciones --> **Quiero avanzar firmemente** / **Yo...no estoy seguro** 
3 Seleccionar una de las opciones y continuar con los diálogos hasta llegar a esta escena.

Frecuencia: 6/6

Workaround: No existe.

Video: https://drive.google.com/file/d/10F9RZUqeGZrfwx-ZW6VZtVMQY6ZtScj-/view?usp=sharing

Versión: V0.8

**Comment by LucioRuixo** [comment]
Sí, esto pasaba por un problema en el manejo de corrutinas al hacer que los personajes entren y salgan de escena. Debería estar arreglado en la v0.9 que está en itchio, si lo pudieran comprobar.

**Comment by LucioRuixo** [comment]
Lo probé yo y sí funciona.

**Comment by franciscoduro** [comment]
Probado desde mi lado y también funciona.
