### ISSUE TITLE
[Prologue + Act 1] "los que no teníamos nada teníamos que pelear para vivir"

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#19]
Solo a modo de mejora/consejo, pienso que la frase quedaría mejor de la siguiente forma: "Lo hacíamos para sobrevivir. Los que no teníamos nada, debíamos pelear para sobrevivir".

Frase: ""(Lo hac\xEDamos para sobrevivir, los que no ten\xEDamos nada teniamos que pelear para vivir...)""
Línea: 515
Archivo: Prologue + Act 1.asset
Ubicación: DVJ3-ThePeaceIFoundInYou\Assets\Scriptable Objects\Scenes\Old Noodle
Versión: 0.8
Foto: https://drive.google.com/file/d/1oTxVynWZglWz6z3dbSMsNX3_LitfqMFg/view?usp=sharing

**Comment by LucioRuixo** [comment]
Aviso por acá que esta y todás las demás correcciones gramaticales fueron revisadas y corregidas y sus respectivos issues cerrados.
