### ISSUE TITLE
[Juego del cuchillo] Al hacer click sobre las frutas no sucede nada

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#2]
En muchas ocasiones, al querer "cortar" (haciendo click sobre) las frutas, el juego no selecciona las verduras. De esta forma, no se puede ganar el minijuego.

Pasos de reproducción dentro del juego:
1) Seleccionar "Dirigirse hacia el ruido".
2) Seleccionar "Acercarse con calma".
3) Hacer click sobre una verdura.

Resultados:
El juego no toma la selección de la verdura.

Frecuencia: 3/5

Workaround: no existe.

Video: https://drive.google.com/file/d/1XP4jNoHVKns96G7AmBK_iMnhUN-ylziz/view?usp=sharing

Versión: 0.8

**Comment by LucioRuixo** [comment]
El minijuego funciona de forma que las verduras se cortan al hacer click específicamente con la punta del cuchillo, pero sí, entendemos que no es lo más intuitivo. Todavía falta iterar un poco este minijuego, y se va a poder cortar las verduras cuando hagan contacto con cualquier parte de la hoja del cuchillo.

**Comment by pedroacastagnola** [comment]
Hola, Lucio! Perfecto, entendido. Más allá del tamaño del contacto del cuchillo, en el video se muestra que hay momentos en los cuales hago click con la punta del cuchillo en la verdura pero no se selecciona. Cualquier cosa, probalo cuando puedas y avisame.

**Comment by LucioRuixo** [comment]
Algunas verduras necesitan más clicks que otras para cortarse, y hasta que no se cortan del todo no cambia el color del sprite, debe ser eso. Nos olvidamos de especificarlo pero de nuevo, está bastante verde por ahora.
