### ISSUE TITLE
Comunicación entre equipos testing - desarrollo

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#20]
Hola, Lucio. ¿Cómo estás?
Nos gustaría tener un contacto más directo con vos para mejorar la comunicación entre todos nosotros. Podemos hacerlo por mail, whatsapp, discord (tenemos un grupo del tp), lo que mejor te venga. Avisanos qué preferís.

Abrazo!

**Comment by LucioRuixo** [comment]
Si me pasás tu mail te doy mi número así nos comunicamos por whatsapp.

**Comment by pedroacastagnola** [comment]
Hola, Lucio. Mi mail es pedroacastagnola@gmail.com. Enviame tu número y armo el grupo. Saludos!

**Comment by LucioRuixo** [comment]
Ahí te mandé mi número por mail.
