### ISSUE TITLE
[Download] https://the-peace-i-found-in-you.itch.io/the-peace-i-found-in-you

### ISSUE THREAD

**Issue by franciscoduro** [LucioRuixo/DVJ3-VisualNovel#28]
Lucio,

Veo que en la página de Itch.io no figura el link de descarga.

Link: https://the-peace-i-found-in-you.itch.io/the-peace-i-found-in-you

**Comment by LucioRuixo** [comment]
Le había dado a "ocultar archivo" sin querer. Ya está arreglado.
