### ISSUE TITLE
[Unity] El texto de los diálogos no se muestra de forma correcta al modificar la resolución de la pantalla

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#3]
En el editor de Unity, al modificar la resolución del juego por una que no sea 16:9, el texto de los diálogos se muestra desfasado de los cuadros.

Pasos de reproducción en Unity:
1) Correr escena Main Menu.
2) Modificar resolución a otra que no sea 16:9.

Resultados:
El texto de los diálogos se desfasará con respecto a los cuadros.

Frecuencia: 5/5

Workaround: no existe.

Video: https://drive.google.com/file/d/1WE60dIm0Oxu5PbHL_toXwf7_Wkr-osrl/view?usp=sharing

Versión: 0.8

**Comment by LucioRuixo** [comment]
Ahí hice que se mantenga el aspect ratio del cuadro de diálogo y todos sus elementos se escalan correctamente. También hice ajustes parecidos en el menú principal. Agradecería si pudieran chequear si no hay otros elementos de UI que no se escalen correctamente.

**Comment by pedroacastagnola** [comment]
Lucio, genial. Se ve muy bien el juego. 
Te consulto sobre algo nada más antes de cerrarlo:
¿Es relevante probar la resolución del Free Aspect? No sé en qué casos se usaría. Es la única que estaría fallando. Te muestro:

https://drive.google.com/file/d/13tKxXBQqlFHsqhBY7oehwuHBKxZrhKqh/view?usp=sharing

Espero tu respuesta!
Saludos

**Comment by LucioRuixo** [comment]
Na, se setea por default en Unity hasta que definas una resolución, pero no es relevante. Gracias por revisar el resto de la UI.
