### ISSUE TITLE
[Seijun`s Route] Desaparecen personajes de la escena

### ISSUE THREAD

**Issue by franciscoduro** [LucioRuixo/DVJ3-VisualNovel#30]
En la ruta de Seinju, luego de que el Protagonista quede ciego durante unos momentos, en las siguientes escenas desaparecen los personajes de Sachi y Seijun mientras continúan hablando.

Pasos para reproducir
Seguir la Ruta de Seinjun: 
1 ignorar el ruido 
2 quiero avanzar firmemente 
3 aceptar la promesa

Frecuencia: 4/4

Workaround: No Existe

Video: https://drive.google.com/file/d/1mg7U2Q8-Nn16lSVvZjwDPf1izrH7rxlv/view?usp=sharing

**Comment by LucioRuixo** [comment]
Retiramos una ilustración del juego en esa parte y me había olvidado de hacer que los personajes ya no salgan de escena, por eso desaparecen. Está arreglado a partir de la v0.10.

**Comment by franciscoduro** [comment]
Acabo de comprobarlo y efectivamente está fixeado.
