### ISSUE TITLE
Cuando se carga una partida, no hay música

### ISSUE THREAD

**Issue by JustinoPazCruz** [LucioRuixo/DVJ3-VisualNovel#31]
Hay momentos puntuales en el juego donde se activa la música (Ya sea cuando se entra a una nueva zona o aparece un personaje), pero si se carga una partida después de ese momento puntual, no va a haber música hasta el próximo momento puntual.

Pasos de reproducción:
Esperar a que la música aparezca/cambie
Guardar Partida
Salir
Cargar Partida

Frecuencia: 10/10

Versión: 0.9

Video: https://drive.google.com/file/d/1gyDUiOh79B28EkdAHXRHeqRjKk_qpCxY/view?usp=sharing

**Comment by LucioRuixo** [comment]
Sí, y lo mismo pasa con los efectos visuales. Pasa porque actualmente no estoy guardanto la data de qué música y efectos estaban activos al momento de guardar la partida. Estoy trabajando en eso.

**Comment by LucioRuixo** [comment]
Mi error, con los efectos visuales ya no pasaba, solo con la música. Ya está arreglado.
