### ISSUE TITLE
Las imágenes que aparecen en el menú principal son inconsistentes 

### ISSUE THREAD

**Issue by JustinoPazCruz** [LucioRuixo/DVJ3-VisualNovel#32]
En el menú principal, las imágenes que aparecen son aleatorias, y a veces no transicionan bien de una a otra, por ejemplo, mientras que a veces hay una animación para la transición, hay veces en las que no. Y así. Otras veces aparece una imagen por muy poco tiempo y se va.

https://drive.google.com/file/d/1J3bYxk4S04dCEJmh12E68STJrnHi1jgx/view

**Comment by LucioRuixo** [comment]
Lo había notado y está arreglado creo que a partir de la v0.10.
