### ISSUE TITLE
[Minijuego Frutas] Se muestra mensaje de éxito en inglés al ganarlo

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#34]
Al ganar el minijuego de las frutas, el sistema muestra un cartel de éxito en inglés "You won". No respeta el idioma original del juego.

Versión: 0.10
Imagen: https://drive.google.com/file/d/1lJKFZLEKi-pCfQQlUL8Mmzol90wj52uc/view?usp=sharing

**Comment by LucioRuixo** [comment]
Mi error. Cambié ese texto por "¡Ganaste!" y el de derrota por "¡Perdiste!", que también estaba en inglés.
