### ISSUE TITLE
[Cargar] Al cargar el juego, te atrasa 2 diagolos

### ISSUE THREAD

**Issue by mrossetto13** [LucioRuixo/DVJ3-VisualNovel#4]
Al momento de guardar y cargar, el juego carga 2 diálogos para atrás de donde se guardo

Pasos de reproducción:

1) Abrir el juego.
2) Avanzar un poco en la historia. (No hace falta un punto exacto)
3) Guardar la partida.
4) Salir de la partida.
5) Cargar la partida.

Frecuencia: 5/5

Workaround: no existe.

Video: https://drive.google.com/file/d/19K0_2O1YN0-Z2iDCFyWzh5RNSvLHVq7p/view?usp=sharing

Versión: 0.8

**Comment by LucioRuixo** [comment]
No te atrasa necesariamente dos diálogos, lo que pasaba es que los diálogos están almacenados en nodos, y cada vez que cargabas la partida te llevaba de vuelta al principio del nodo. Esto era porque no se estaba guardando el índice de la frase mostrada en pantalla a la hora de guardar. Ya está arreglado.
