### ISSUE TITLE
[Seijun - A1S4] "Seguro estas cansado toda-"

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#42]
1. Falta la tilde en "estas".
2. Luego de "cansado", poner algún signo de puntuación.

Frase: "Seguro estas cansado toda-"
Línea: 363
Archivo: Seijun - A1S4.asset
Ubicación: Assets\Scriptable Objects\Scenes\Seijun's Route
Versión: 0.10
Imagen: https://drive.google.com/file/d/1ZCjdq72YjmP8it_ToyllHpHWhpXCaoe8/view?usp=sharing

**Comment by pedroacastagnola** [comment]
Lucio, cómo estás?
El 1. está bien corregido.
El 2. persiste.

Gracias
Pedro

**Comment by LucioRuixo** [comment]
En el caso del punto 2 que me marcaste, la frase que debería decir el personaje antes de que lo interrumpan es "Seguro estás cansado todavía.", y no me parece que deba llevar signo de puntuación. En todo caso podría cambiarse a algo como "Seguro todavía estás cansa-." para que la frase completa se intuya mejor, no sé qué te parece a vos.

**Comment by pedroacastagnola** [comment]
Hola, Lucio! disculpas por la demora. 
Ahí entendí! Perfecto, sí. Creo que la intención se entiende mejor si lo cortás en "cansa-", pensaba que quería decir algo con la palabra "toda".

Gracias

**Comment by LucioRuixo** [comment]
Ahí modifiqué la frase para que se entienda mejor.
