### ISSUE TITLE
[Cargar Partida] Personajes desaparecen al cargar una partida

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#43]
Al cargar una partida, el juego no muestra los personajes en el diálogo. Sí lo hace luego, al terminar la escena y comenzar una nueva.

Pasos de reproducción:

1) Llegar al momento del juego posterior al minijuego de las frutas.
2) Guardar la partida.
3) Salir.
4) Cargar la partida.

Resultados:
El juego no mostrará los personajes que participan de la conversación.

Frecuencia: 2/2

Workaround: no existe.

Video: https://drive.google.com/file/d/1_fuUexLXyHdBRdrDPMdDJeiRzxb-KDvs/view?usp=sharing

Versión: 0.10

**Comment by LucioRuixo** [comment]
Esto pasa solo cuando se guarda la partida en formato JSON,  no? Si es así, ya está arreglado y va a funcionar para la próxima versión.

**Comment by pedroacastagnola** [comment]
Hola, Lucio. 
- Cuando se guarda en formato Json los personajes desaparecen.
- Cuando no se guarda en formato Json los personajes se duplican en la próxima escena.

Te paso imagen del segundo caso. Realicé los mismos pasos que indiqué en la descripción del bug, excepto que en lugar de elegir guardar en formato Json, esta vez puse que no.
Cuando cargues la partida, al principio no van a figurar duplicados. Avanzá hacia la próxima escena y ahí recién vas a ver los duplicados.

**Comment by pedroacastagnola** [comment]
Me olvidé de pasarte la imagen:
https://drive.google.com/file/d/1aebUj68fzBwEXt-Sa7xOHXGiRylnIH8h/view?usp=sharing

**Comment by LucioRuixo** [comment]
Lo probé y lo del duplicado de personajes no me pasó, pero creo que lo que lo causaba es un error que ya resolví, donde había una escena que se estaba reproduciendo dos veces. Debe haber sido esta misma escena, y que al principio de ella se daba la orden de hacer aparecer a los personajes pero, como estaban mal las escenas, no se daba antes la orden de que desaparezcan y por eso se duplicaban. Para la v0.11 no debería pasar más.

**Comment by pedroacastagnola** [comment]
Testeado Ok!
