### ISSUE TITLE
[Camino Hoshi - opción Acercarse rápidamente] Diálogos desaparecen y el juego no permite continuar

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#50]
Durante una conversación entre Tadao y Hoshi, los diálogos desaparecen y el juego no permite continuar.

Pasos de reproducción:
1. Elegir opción de Acercarse al ruido.
2. Elegir opción Acercarse rápidamente.

Resultados
Los diálogos  y la ventana de acciones desaparecerán y el juego no permitirá continuar.

Frecuencia: 2/2

Workaround: no existe. Aunque si se elige la opción de Acercarse con cuidado, el juego no se traba en la conversación.

Video: https://drive.google.com/file/d/13LwR3r10yl6EH6VPrY1rEoVMifR0EaEJ/view?usp=sharing

Versión: 0.11

**Comment by LucioRuixo** [comment]
Era un error en el armado de la escena, no debería pasar más.
