### ISSUE TITLE
[Seijun] Repetición de dialogos, al estar con los fantasmas

### ISSUE THREAD

**Issue by mrossetto13** [LucioRuixo/DVJ3-VisualNovel#52]
Luego de que te encontrás a los espíritus en el bosque y te salvan, se repite los diálogos en una pantalla negra y después de pasar todos los diálogos.

No tengo evidencia, no lo pude volver a reproducir.

Versión: V0.11

**Comment by LucioRuixo** [comment]
Había un dato que me estaba olvidando de almacenar en los archivos de guardado, lo que causaba un problema al cargar la primera escena de cada ruta (en el caso de la ruta de Seijun, la escena de los espíritus). No debería estar pasando más.
