### ISSUE TITLE
[Transicion de personajes] El modelo de los personajes queda en la pantalla cuando estos se van

### ISSUE THREAD

**Issue by mrossetto13** [LucioRuixo/DVJ3-VisualNovel#53]
Esto sucede en el camino de Seijun y Sachi.

Evidencia:
https://drive.google.com/file/d/1K7A8ftmzJcq4cfQrjVprxxOBjlmkT7S7/view?usp=sharing
https://drive.google.com/file/d/12qCYPdT-VopIadx2DD1CpFuPK9ei_cgs/view?usp=sharing
https://drive.google.com/file/d/12FisFEAzP3Dz8doYnHEdmNXTnMQejyM0/view?usp=sharing
https://drive.google.com/file/d/1_GGSNY4eHaGoPJ1T5uJZ2wiUeEFNBa3K/view?usp=sharing

Version: V0.11

**Comment by LucioRuixo** [comment]
No estaba haciendo que algunos personajes salgan completamente de pantalla, y una vez terminaban de moverse no los estaba borrando. Debería estar arreglado para la próxima versión.
