### ISSUE TITLE
[Camino Seijun] Seijun no se saca la máscara en el momento que debería

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#54]
Seijun le dice a P que va a mostrarse pero el juego no le saca la máscara al personaje de Seijun en ese momento como ocurría antes. Recién se lo ve al personaje sin la máscara dentro de la cabaña.

Pasos de reproducción:
1. Elegir la opción Ignorar sonido (opción 2)
2. Avanzar hacia la luz firmemente (opción 1)
3. Aceptar promesa (opción 1)

Resultados
Seijun no se sacará su máscara como debería.

Frecuencia: 3/3

Video: https://drive.google.com/file/d/1JG_hsoUl-3QGsCp8wDot7txdExT1HewV/view?usp=sharing
Versión: 0.13

**Comment by LucioRuixo** [comment]
Este error había surgido cuando implementé la animación de Seijun. Ya lo arreglé y comprobé que no pasa más.
