### ISSUE TITLE
[Camino Seijun] El personaje de Seijun se rompe (queda sin cuerpo)

### ISSUE THREAD

**Issue by pedroacastagnola** [LucioRuixo/DVJ3-VisualNovel#55]
Cuando Seijun le dice al Protagonista "seguro todavía estás cansado", apenas llegan al santuario, el personaje de Seijun se rompe (queda sin cuerpo). Vuelve a verse bien el personaje cuando aparece Sachi.

Pasos de reproducción:
1. Elegir "Ignorar Sonido"
2. Elegir "Avanzar firmemente"

Resultados: el personaje de Seijun se rompe.
Frecuencia: 2/2
Imagen: https://drive.google.com/file/d/1Hkhi6-4mTJ8OiHPwkk59LsBgSXUmGzlo/view?usp=sharing

**Comment by pedroacastagnola** [comment]
Versión 14!

**Comment by LucioRuixo** [comment]
Que raro, lo probé y no me pasó ni en Unity ni en la build. Por las dudas, ¿la build la descargaste el mismo día que abriste el issue? Porque reemplazé el .zip de esta versión un par de veces por errores que había, por ahí te bajaste una versión anterior que estaba rota. Otra cosa, ¿en qué resolución jugás?

**Comment by pedroacastagnola** [comment]
Buenas. Me lo volví a bajar y no sucedió el error. El juego corre en pantalla completa como siempre. La resolución de pantalla de mi notebook es 1366 x 768 con una escala al 100%.
